[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paysim-pipeline"
version = "0.1.0"
description = "Pipeline ETL para el dataset PaySim"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "André Velásquez", email = "valszaque@gmail.com" }
]
keywords = ["etl", "SQL", "data", "analysis", "BI", "pipeline", "paysim"]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]
dependencies = [
    "alembic==1.18.5",
    "duckdb==1.5.4",
    "kagglehub==1.0.2",
    "matplotlib==3.11.0",
    "missingno==0.5.2",
    "pandas==3.0.3",
    "pandera[pandas]==0.32.1",
    "psycopg2==2.9.12",
    "pyarrow==25.0.0",
    "python-dotenv==1.2.2",
    "seaborn==0.13.2",
    "SQLAlchemy==2.0.51"
]

[project.scripts]
paysim-pipeline = "src.pipeline:main"

[dependency-groups]
dev = [
    "ipykernel==7.3.0",
    "jupyterlab==4.6.2",
    "ruff==0.15.21"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src", "src.*"]

[tool.ruff]
src = ["src"]
line-length = 90
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "C4", "N", "B", "UP"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"src/validate.py" = ["N815"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
