"""esquema inicial de paysim

Revision ID: 7bf86c6814aa
Revises: 
Create Date: 2026-07-18 23:58:18.447252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf86c6814aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paysim',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('name_orig', sa.Text(), nullable=False),
    sa.Column('oldbalance_orig', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('newbalance_orig', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('name_dest', sa.Text(), nullable=False),
    sa.Column('oldbalance_dest', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('newbalance_dest', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_flagged_fraud', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=False),
    sa.Column('simulation_day', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("type IN ('PAYMENT','TRANSFER','CASH_OUT','CASH_IN','DEBIT')", name=op.f('ck_paysim_type_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_paysim_amount_nonneg')),
    sa.CheckConstraint('hour_of_day BETWEEN 0 AND 23', name=op.f('ck_paysim_hour_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paysim'))
    )
    with op.batch_alter_table('paysim', schema=None) as batch_op:
        batch_op.create_index('ix_paysim_is_fraud_true', ['is_fraud'], unique=False, postgresql_where=sa.text('is_fraud = true'))
        batch_op.create_index('ix_paysim_name_dest', ['name_dest'], unique=False)
        batch_op.create_index('ix_paysim_name_orig', ['name_orig'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paysim', schema=None) as batch_op:
        batch_op.drop_index('ix_paysim_name_orig')
        batch_op.drop_index('ix_paysim_name_dest')
        batch_op.drop_index('ix_paysim_is_fraud_true', postgresql_where=sa.text('is_fraud = true'))

    op.drop_table('paysim')
    # ### end Alembic commands ###
